-- ============================================================
-- TEST 100K PATIENT USERS - CHECK
-- Verifies generated Oracle users, patient rows, role grants, and mapping.
--
-- Run as: BVDBA, SYS, SYSTEM, or an admin user with dictionary access
-- ============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;
SET LINESIZE 220;
SET PAGESIZE 200;

COLUMN CHECK_NAME FORMAT A42;
COLUMN CHECK_VALUE FORMAT A30;
COLUMN USERNAME FORMAT A16;
COLUMN ACCOUNT_STATUS FORMAT A20;
COLUMN GRANTED_ROLE FORMAT A24;
COLUMN MABN FORMAT A12;
COLUMN TENBN FORMAT A34;
COLUMN ORACLE_USERNAME FORMAT A18;
COLUMN ROLE_STATUS FORMAT A14;
COLUMN PATIENT_STATUS FORMAT A14;

PROMPT ===== 1. Count generated Oracle users =====
SELECT 'GENERATED_ORACLE_USERS' AS CHECK_NAME,
       TO_CHAR(COUNT(*)) AS CHECK_VALUE
FROM DBA_USERS
WHERE REGEXP_LIKE(USERNAME, '^BN[0-9]{6}$')
  AND USERNAME BETWEEN 'BN000001' AND 'BN100000';

PROMPT
PROMPT ===== 2. Count generated patient rows with safe marker =====
SELECT 'GENERATED_PATIENT_ROWS' AS CHECK_NAME,
       TO_CHAR(COUNT(*)) AS CHECK_VALUE
FROM BVDBA.BENHNHAN
WHERE REGEXP_LIKE(MABN, '^BN[0-9]{6}$')
  AND MABN BETWEEN 'BN000001' AND 'BN100000'
  AND ORACLE_USERNAME = MABN
  AND CCCD = '9' || LPAD(TO_NUMBER(SUBSTR(MABN, 3)), 11, '0')
  AND TENBN LIKE N'[TEST100K]%';

PROMPT
PROMPT ===== 3. Sample users =====
SELECT U.USERNAME,
       U.ACCOUNT_STATUS,
       CASE WHEN RP.GRANTED_ROLE IS NOT NULL THEN RP.GRANTED_ROLE ELSE '(NO PATIENT ROLE)' END AS GRANTED_ROLE
FROM (
    SELECT 'BN000001' USERNAME FROM DUAL UNION ALL
    SELECT 'BN000100' FROM DUAL UNION ALL
    SELECT 'BN001000' FROM DUAL UNION ALL
    SELECT 'BN010000' FROM DUAL UNION ALL
    SELECT 'BN100000' FROM DUAL
) S
LEFT JOIN DBA_USERS U
       ON U.USERNAME = S.USERNAME
LEFT JOIN DBA_ROLE_PRIVS RP
       ON RP.GRANTEE = S.USERNAME
      AND RP.GRANTED_ROLE IN ('RL_BENHNHAN', 'ROLE_BENHNHAN_DEMO')
ORDER BY S.USERNAME;

PROMPT
PROMPT ===== 4. Sample patient mapping =====
SELECT B.MABN,
       B.TENBN,
       B.CCCD,
       B.ORACLE_USERNAME,
       CASE
           WHEN U.USERNAME IS NOT NULL THEN 'USER_OK'
           ELSE 'NO_USER'
       END AS USER_STATUS,
       CASE
           WHEN RP.GRANTED_ROLE IS NOT NULL THEN 'ROLE_OK'
           ELSE 'NO_ROLE'
       END AS ROLE_STATUS
FROM BVDBA.BENHNHAN B
LEFT JOIN DBA_USERS U
       ON U.USERNAME = B.ORACLE_USERNAME
LEFT JOIN DBA_ROLE_PRIVS RP
       ON RP.GRANTEE = B.ORACLE_USERNAME
      AND RP.GRANTED_ROLE IN ('RL_BENHNHAN', 'ROLE_BENHNHAN_DEMO')
WHERE B.MABN IN ('BN000001', 'BN000100', 'BN001000', 'BN010000', 'BN100000')
ORDER BY B.MABN;

PROMPT
PROMPT ===== 5. Mapping problems =====
SELECT 'PATIENT_WITHOUT_ORACLE_USER' AS CHECK_NAME,
       TO_CHAR(COUNT(*)) AS CHECK_VALUE
FROM BVDBA.BENHNHAN B
WHERE REGEXP_LIKE(B.MABN, '^BN[0-9]{6}$')
  AND B.MABN BETWEEN 'BN000001' AND 'BN100000'
  AND B.TENBN LIKE N'[TEST100K]%'
  AND NOT EXISTS (
      SELECT 1 FROM DBA_USERS U WHERE U.USERNAME = B.ORACLE_USERNAME
  )
UNION ALL
SELECT 'USER_WITHOUT_PATIENT_ROW',
       TO_CHAR(COUNT(*))
FROM DBA_USERS U
WHERE REGEXP_LIKE(U.USERNAME, '^BN[0-9]{6}$')
  AND U.USERNAME BETWEEN 'BN000001' AND 'BN100000'
  AND NOT EXISTS (
      SELECT 1
      FROM BVDBA.BENHNHAN B
      WHERE B.ORACLE_USERNAME = U.USERNAME
        AND B.MABN = U.USERNAME
        AND B.TENBN LIKE N'[TEST100K]%'
  )
UNION ALL
SELECT 'USER_WITHOUT_PATIENT_ROLE',
       TO_CHAR(COUNT(*))
FROM DBA_USERS U
WHERE REGEXP_LIKE(U.USERNAME, '^BN[0-9]{6}$')
  AND U.USERNAME BETWEEN 'BN000001' AND 'BN100000'
  AND NOT EXISTS (
      SELECT 1
      FROM DBA_ROLE_PRIVS RP
      WHERE RP.GRANTEE = U.USERNAME
        AND RP.GRANTED_ROLE IN ('RL_BENHNHAN', 'ROLE_BENHNHAN_DEMO')
  );

PROMPT
PROMPT ===== 6. SQL tests for patient isolation =====
PROMPT Run these in separate SQL Developer connections:
PROMPT
PROMPT -- Connection A: username BN000001 / password Bn@123456
PROMPT SELECT USER AS CURRENT_USER FROM DUAL;
PROMPT SELECT MABN, TENBN, ORACLE_USERNAME FROM BVDBA.VW_BN_THONGTIN_CANHAN;
PROMPT SELECT COUNT(*) AS OTHER_ROWS FROM BVDBA.VW_BN_THONGTIN_CANHAN WHERE ORACLE_USERNAME <> USER;
PROMPT -- Expected: one row with ORACLE_USERNAME = BN000001, OTHER_ROWS = 0.
PROMPT
PROMPT -- Connection B: username BN000002 / password Bn@123456
PROMPT SELECT USER AS CURRENT_USER FROM DUAL;
PROMPT SELECT MABN, TENBN, ORACLE_USERNAME FROM BVDBA.VW_BN_THONGTIN_CANHAN;
PROMPT SELECT COUNT(*) AS OTHER_ROWS FROM BVDBA.VW_BN_THONGTIN_CANHAN WHERE ORACLE_USERNAME <> USER;
PROMPT -- Expected: one row with ORACLE_USERNAME = BN000002, OTHER_ROWS = 0.
PROMPT
PROMPT -- Direct access to BVDBA.BENHNHAN should normally be denied to patient users.
PROMPT SELECT MABN, TENBN FROM BVDBA.BENHNHAN WHERE MABN = 'BN000002';

